services:
  front:
    build:
      dockerfile: ../dev/front/Dockerfile.ssr
    container_name: archifoot_front_ssr
    ports:
      - "4200:4200"
      - "4000:4000"
    command:
      - bash
      - -lc
      - |
        npm ci &&
        npm run build:ssr &&
        npm run serve:ssr
