<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260130222601 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE category CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(120) DEFAULT NULL, CHANGE gender gender VARCHAR(10) DEFAULT NULL, CHANGE age_min age_min INT DEFAULT NULL, CHANGE age_max age_max INT DEFAULT NULL');
        $this->addSql('ALTER TABLE city DROP FOREIGN KEY `fk_city_country_id`');
        $this->addSql('ALTER TABLE city DROP FOREIGN KEY `fk_city_region_id`');
        $this->addSql('ALTER TABLE city CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE country_id country_id INT DEFAULT NULL, CHANGE region_id region_id INT DEFAULT NULL, CHANGE name name VARCHAR(150) DEFAULT NULL');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B0234F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT FK_2D5B023498260155 FOREIGN KEY (region_id) REFERENCES region (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE city RENAME INDEX fk_city_country_id TO IDX_2D5B0234F92F3E70');
        $this->addSql('ALTER TABLE city RENAME INDEX fk_city_region_id TO IDX_2D5B023498260155');
        $this->addSql('ALTER TABLE club DROP FOREIGN KEY `fk_club_city_id`');
        $this->addSql('ALTER TABLE club DROP FOREIGN KEY `fk_club_country_id`');
        $this->addSql('ALTER TABLE club DROP FOREIGN KEY `fk_club_region_id`');
        $this->addSql('ALTER TABLE club CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(200) DEFAULT NULL, CHANGE short_name short_name VARCHAR(80) DEFAULT NULL, CHANGE country_id country_id INT DEFAULT NULL, CHANGE city_id city_id INT DEFAULT NULL, CHANGE region_id region_id INT DEFAULT NULL, CHANGE founded_year founded_year INT DEFAULT NULL');
        $this->addSql('ALTER TABLE club ADD CONSTRAINT FK_B8EE3872F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE club ADD CONSTRAINT FK_B8EE38728BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE club ADD CONSTRAINT FK_B8EE387298260155 FOREIGN KEY (region_id) REFERENCES region (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE club RENAME INDEX fk_club_country_id TO IDX_B8EE3872F92F3E70');
        $this->addSql('ALTER TABLE club RENAME INDEX fk_club_city_id TO IDX_B8EE38728BAC62AF');
        $this->addSql('ALTER TABLE club RENAME INDEX fk_club_region_id TO IDX_B8EE387298260155');
        $this->addSql('ALTER TABLE coach DROP FOREIGN KEY `fk_coach_person_id`');
        $this->addSql('ALTER TABLE coach CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE person_id person_id INT DEFAULT NULL, CHANGE role role VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE coach ADD CONSTRAINT FK_3F596DCC217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE coach RENAME INDEX fk_coach_person_id TO IDX_3F596DCC217BBB47');
        $this->addSql('ALTER TABLE competition DROP FOREIGN KEY `fk_competition_category_id`');
        $this->addSql('ALTER TABLE competition CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(200) DEFAULT NULL, CHANGE type type VARCHAR(30) DEFAULT NULL, CHANGE organizer organizer VARCHAR(120) DEFAULT NULL, CHANGE category_id category_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE competition ADD CONSTRAINT FK_B50A2CB112469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE competition RENAME INDEX fk_competition_category_id TO IDX_B50A2CB112469DE2');
        $this->addSql('ALTER TABLE country CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(150) DEFAULT NULL, CHANGE iso2 iso2 VARCHAR(2) DEFAULT NULL, CHANGE iso3 iso3 VARCHAR(3) DEFAULT NULL, CHANGE fifa_code fifa_code VARCHAR(3) DEFAULT NULL');
        $this->addSql('ALTER TABLE division DROP FOREIGN KEY `fk_division_country_id`');
        $this->addSql('ALTER TABLE division CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(120) DEFAULT NULL, CHANGE level level INT DEFAULT NULL, CHANGE country_id country_id INT DEFAULT NULL, CHANGE in_championship in_championship TINYINT DEFAULT NULL');
        $this->addSql('ALTER TABLE division ADD CONSTRAINT FK_10174714F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE division RENAME INDEX fk_division_country_id TO IDX_10174714F92F3E70');
        $this->addSql('ALTER TABLE edition DROP FOREIGN KEY `fk_edition_competition_id`');
        $this->addSql('ALTER TABLE edition DROP FOREIGN KEY `fk_edition_division_id`');
        $this->addSql('ALTER TABLE edition DROP FOREIGN KEY `fk_edition_season_id`');
        $this->addSql('ALTER TABLE edition CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE competition_id competition_id INT DEFAULT NULL, CHANGE season_id season_id INT DEFAULT NULL, CHANGE name name VARCHAR(120) DEFAULT NULL, CHANGE division_id division_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE edition ADD CONSTRAINT FK_A891181F7B39D312 FOREIGN KEY (competition_id) REFERENCES competition (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE edition ADD CONSTRAINT FK_A891181F4EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE edition ADD CONSTRAINT FK_A891181F41859289 FOREIGN KEY (division_id) REFERENCES division (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE edition RENAME INDEX fk_edition_season_id TO IDX_A891181F4EC001D1');
        $this->addSql('ALTER TABLE edition RENAME INDEX fk_edition_division_id TO IDX_A891181F41859289');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY `fk_fixture_category_id`');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY `fk_fixture_city_id`');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY `fk_fixture_competition_id`');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY `fk_fixture_country_id`');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY `fk_fixture_division_id`');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY `fk_fixture_edition_id`');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY `fk_fixture_matchday_id`');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY `fk_fixture_season_id`');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY `fk_fixture_stadium_id`');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY `fk_fixture_stage_id`');
        $this->addSql('ALTER TABLE fixture CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE external_match_no external_match_no INT DEFAULT NULL, CHANGE competition_id competition_id INT DEFAULT NULL, CHANGE season_id season_id INT DEFAULT NULL, CHANGE edition_id edition_id INT DEFAULT NULL, CHANGE stage_id stage_id INT DEFAULT NULL, CHANGE matchday_id matchday_id INT DEFAULT NULL, CHANGE division_id division_id INT DEFAULT NULL, CHANGE category_id category_id INT DEFAULT NULL, CHANGE match_date match_date DATE DEFAULT NULL, CHANGE stadium_id stadium_id INT DEFAULT NULL, CHANGE city_id city_id INT DEFAULT NULL, CHANGE country_id country_id INT DEFAULT NULL, CHANGE played played TINYINT DEFAULT NULL, CHANGE is_official is_official TINYINT DEFAULT NULL, CHANGE notes notes LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT FK_5E540EE7B39D312 FOREIGN KEY (competition_id) REFERENCES competition (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT FK_5E540EE4EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT FK_5E540EE74281A5E FOREIGN KEY (edition_id) REFERENCES edition (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT FK_5E540EE2298D193 FOREIGN KEY (stage_id) REFERENCES stage (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT FK_5E540EE3D90D21B FOREIGN KEY (matchday_id) REFERENCES matchday (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT FK_5E540EE41859289 FOREIGN KEY (division_id) REFERENCES division (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT FK_5E540EE12469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT FK_5E540EE7E860E36 FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT FK_5E540EE8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT FK_5E540EEF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture RENAME INDEX fk_fixture_matchday_id TO IDX_5E540EE3D90D21B');
        $this->addSql('ALTER TABLE fixture RENAME INDEX fk_fixture_division_id TO IDX_5E540EE41859289');
        $this->addSql('ALTER TABLE fixture RENAME INDEX fk_fixture_category_id TO IDX_5E540EE12469DE2');
        $this->addSql('ALTER TABLE fixture RENAME INDEX fk_fixture_stadium_id TO IDX_5E540EE7E860E36');
        $this->addSql('ALTER TABLE fixture RENAME INDEX fk_fixture_city_id TO IDX_5E540EE8BAC62AF');
        $this->addSql('ALTER TABLE fixture RENAME INDEX fk_fixture_country_id TO IDX_5E540EEF92F3E70');
        $this->addSql('ALTER TABLE fixture_participant DROP FOREIGN KEY `fk_fixture_participant_fixture_id`');
        $this->addSql('ALTER TABLE fixture_participant DROP FOREIGN KEY `fk_fixture_participant_team_id`');
        $this->addSql('ALTER TABLE fixture_participant CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE fixture_id fixture_id INT DEFAULT NULL, CHANGE team_id team_id INT DEFAULT NULL, CHANGE role role VARCHAR(1) DEFAULT NULL, CHANGE score score INT DEFAULT NULL, CHANGE score_extra score_extra INT DEFAULT NULL, CHANGE score_penalty score_penalty INT DEFAULT NULL, CHANGE is_winner is_winner TINYINT DEFAULT NULL, CHANGE venue_role venue_role VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE fixture_participant ADD CONSTRAINT FK_6592938CE524616D FOREIGN KEY (fixture_id) REFERENCES fixture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fixture_participant ADD CONSTRAINT FK_6592938C296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE import_batch DROP FOREIGN KEY `fk_import_batch_source_file_id`');
        $this->addSql('ALTER TABLE import_batch CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE source_file_id source_file_id INT DEFAULT NULL, CHANGE entity entity VARCHAR(50) DEFAULT NULL, CHANGE status status VARCHAR(20) DEFAULT NULL, CHANGE inserted inserted INT DEFAULT NULL, CHANGE updated updated INT DEFAULT NULL, CHANGE skipped skipped INT DEFAULT NULL, CHANGE started_at started_at DATETIME DEFAULT NULL, CHANGE finished_at finished_at DATETIME DEFAULT NULL, CHANGE error error LONGTEXT DEFAULT NULL');
        $this->addSql('ALTER TABLE import_batch ADD CONSTRAINT FK_155EFD1ADA14C104 FOREIGN KEY (source_file_id) REFERENCES source_file (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE import_batch RENAME INDEX fk_import_batch_source_file_id TO IDX_155EFD1ADA14C104');
        $this->addSql('ALTER TABLE match_card DROP FOREIGN KEY `fk_match_card_fixture_id`');
        $this->addSql('ALTER TABLE match_card DROP FOREIGN KEY `fk_match_card_player_id`');
        $this->addSql('ALTER TABLE match_card DROP FOREIGN KEY `fk_match_card_team_id`');
        $this->addSql('ALTER TABLE match_card CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE fixture_id fixture_id INT DEFAULT NULL, CHANGE team_id team_id INT DEFAULT NULL, CHANGE player_id player_id INT DEFAULT NULL, CHANGE player_text player_text VARCHAR(200) DEFAULT NULL, CHANGE minute minute VARCHAR(8) DEFAULT NULL, CHANGE card_type card_type VARCHAR(5) DEFAULT NULL, CHANGE reason reason VARCHAR(200) DEFAULT NULL');
        $this->addSql('ALTER TABLE match_card ADD CONSTRAINT FK_777B29A1E524616D FOREIGN KEY (fixture_id) REFERENCES fixture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE match_card ADD CONSTRAINT FK_777B29A1296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE match_card ADD CONSTRAINT FK_777B29A199E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE match_card RENAME INDEX fk_match_card_fixture_id TO IDX_777B29A1E524616D');
        $this->addSql('ALTER TABLE match_card RENAME INDEX fk_match_card_team_id TO IDX_777B29A1296CD8AE');
        $this->addSql('ALTER TABLE match_card RENAME INDEX fk_match_card_player_id TO IDX_777B29A199E6F5DF');
        $this->addSql('ALTER TABLE match_goal DROP FOREIGN KEY `fk_match_goal_fixture_id`');
        $this->addSql('ALTER TABLE match_goal DROP FOREIGN KEY `fk_match_goal_scorer_id`');
        $this->addSql('ALTER TABLE match_goal DROP FOREIGN KEY `fk_match_goal_team_id`');
        $this->addSql('ALTER TABLE match_goal CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE fixture_id fixture_id INT DEFAULT NULL, CHANGE team_id team_id INT DEFAULT NULL, CHANGE scorer_id scorer_id INT DEFAULT NULL, CHANGE scorer_text scorer_text VARCHAR(200) DEFAULT NULL, CHANGE minute minute VARCHAR(8) DEFAULT NULL, CHANGE goal_type goal_type VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE match_goal ADD CONSTRAINT FK_9DB35A5CE524616D FOREIGN KEY (fixture_id) REFERENCES fixture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE match_goal ADD CONSTRAINT FK_9DB35A5C296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE match_goal ADD CONSTRAINT FK_9DB35A5C43B35028 FOREIGN KEY (scorer_id) REFERENCES player (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE match_goal RENAME INDEX fk_match_goal_team_id TO IDX_9DB35A5C296CD8AE');
        $this->addSql('ALTER TABLE matchday DROP FOREIGN KEY `fk_matchday_edition_id`');
        $this->addSql('ALTER TABLE matchday CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE edition_id edition_id INT DEFAULT NULL, CHANGE label label VARCHAR(50) DEFAULT NULL, CHANGE number number INT DEFAULT NULL, CHANGE start_date start_date DATE DEFAULT NULL, CHANGE end_date end_date DATE DEFAULT NULL');
        $this->addSql('ALTER TABLE matchday ADD CONSTRAINT FK_A95F407674281A5E FOREIGN KEY (edition_id) REFERENCES edition (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE name_alias CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE entity_type entity_type VARCHAR(30) DEFAULT NULL, CHANGE entity_id entity_id INT DEFAULT NULL, CHANGE alias alias VARCHAR(200) DEFAULT NULL, CHANGE normalized normalized VARCHAR(200) DEFAULT NULL');
        $this->addSql('ALTER TABLE national_team DROP FOREIGN KEY `fk_national_team_category_id`');
        $this->addSql('ALTER TABLE national_team DROP FOREIGN KEY `fk_national_team_country_id`');
        $this->addSql('ALTER TABLE national_team CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE country_id country_id INT DEFAULT NULL, CHANGE category_id category_id INT DEFAULT NULL, CHANGE name name VARCHAR(200) DEFAULT NULL');
        $this->addSql('ALTER TABLE national_team ADD CONSTRAINT FK_6034EB55F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE national_team ADD CONSTRAINT FK_6034EB5512469DE2 FOREIGN KEY (category_id) REFERENCES category (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE national_team RENAME INDEX fk_national_team_country_id TO IDX_6034EB55F92F3E70');
        $this->addSql('ALTER TABLE national_team RENAME INDEX fk_national_team_category_id TO IDX_6034EB5512469DE2');
        $this->addSql('ALTER TABLE person DROP FOREIGN KEY `fk_person_birth_city_id`');
        $this->addSql('ALTER TABLE person DROP FOREIGN KEY `fk_person_birth_country_id`');
        $this->addSql('ALTER TABLE person DROP FOREIGN KEY `fk_person_birth_region_id`');
        $this->addSql('ALTER TABLE person DROP FOREIGN KEY `fk_person_nationality_country_id`');
        $this->addSql('ALTER TABLE person CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE full_name full_name VARCHAR(200) DEFAULT NULL, CHANGE birth_date birth_date DATE DEFAULT NULL, CHANGE birth_city_id birth_city_id INT DEFAULT NULL, CHANGE birth_region_id birth_region_id INT DEFAULT NULL, CHANGE birth_country_id birth_country_id INT DEFAULT NULL, CHANGE nationality_country_id nationality_country_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176F0B1CED9 FOREIGN KEY (birth_city_id) REFERENCES city (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD1763E234BFB FOREIGN KEY (birth_region_id) REFERENCES region (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD176C8E7B5D5 FOREIGN KEY (birth_country_id) REFERENCES country (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT FK_34DCD1764A08B118 FOREIGN KEY (nationality_country_id) REFERENCES country (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE person RENAME INDEX fk_person_birth_city_id TO IDX_34DCD176F0B1CED9');
        $this->addSql('ALTER TABLE person RENAME INDEX fk_person_birth_region_id TO IDX_34DCD1763E234BFB');
        $this->addSql('ALTER TABLE person RENAME INDEX fk_person_birth_country_id TO IDX_34DCD176C8E7B5D5');
        $this->addSql('ALTER TABLE person RENAME INDEX fk_person_nationality_country_id TO IDX_34DCD1764A08B118');
        $this->addSql('ALTER TABLE person_club_history DROP FOREIGN KEY `fk_person_club_history_club_id`');
        $this->addSql('ALTER TABLE person_club_history DROP FOREIGN KEY `fk_person_club_history_person_id`');
        $this->addSql('ALTER TABLE person_club_history CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE person_id person_id INT DEFAULT NULL, CHANGE club_id club_id INT DEFAULT NULL, CHANGE role role VARCHAR(20) DEFAULT NULL, CHANGE from_year from_year INT DEFAULT NULL, CHANGE to_year to_year INT DEFAULT NULL, CHANGE note note VARCHAR(200) DEFAULT NULL');
        $this->addSql('ALTER TABLE person_club_history ADD CONSTRAINT FK_C9FC3584217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person_club_history ADD CONSTRAINT FK_C9FC358461190A32 FOREIGN KEY (club_id) REFERENCES club (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE person_club_history RENAME INDEX fk_person_club_history_person_id TO IDX_C9FC3584217BBB47');
        $this->addSql('ALTER TABLE person_club_history RENAME INDEX fk_person_club_history_club_id TO IDX_C9FC358461190A32');
        $this->addSql('ALTER TABLE player DROP FOREIGN KEY `fk_player_person_id`');
        $this->addSql('ALTER TABLE player DROP FOREIGN KEY `fk_player_primary_position_id`');
        $this->addSql('ALTER TABLE player CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE person_id person_id INT DEFAULT NULL, CHANGE primary_position_id primary_position_id INT DEFAULT NULL, CHANGE preferred_foot preferred_foot VARCHAR(10) DEFAULT NULL');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A65217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT FK_98197A65796B4EC7 FOREIGN KEY (primary_position_id) REFERENCES position (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE player RENAME INDEX fk_player_person_id TO IDX_98197A65217BBB47');
        $this->addSql('ALTER TABLE player RENAME INDEX fk_player_primary_position_id TO IDX_98197A65796B4EC7');
        $this->addSql('ALTER TABLE player_national_stats DROP FOREIGN KEY `fk_player_national_stats_player_id`');
        $this->addSql('ALTER TABLE player_national_stats DROP FOREIGN KEY `fk_player_national_stats_team_id`');
        $this->addSql('ALTER TABLE player_national_stats CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE player_id player_id INT DEFAULT NULL, CHANGE team_id team_id INT DEFAULT NULL, CHANGE caps caps INT DEFAULT NULL, CHANGE goals goals INT DEFAULT NULL, CHANGE from_date from_date DATE DEFAULT NULL, CHANGE to_date to_date DATE DEFAULT NULL, CHANGE source_note source_note VARCHAR(200) DEFAULT NULL');
        $this->addSql('ALTER TABLE player_national_stats ADD CONSTRAINT FK_D338C8099E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE player_national_stats ADD CONSTRAINT FK_D338C80296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE player_national_stats RENAME INDEX fk_player_national_stats_player_id TO IDX_D338C8099E6F5DF');
        $this->addSql('ALTER TABLE player_national_stats RENAME INDEX fk_player_national_stats_team_id TO IDX_D338C80296CD8AE');
        $this->addSql('ALTER TABLE position CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE code code VARCHAR(10) DEFAULT NULL, CHANGE label label VARCHAR(80) DEFAULT NULL');
        $this->addSql('ALTER TABLE referee DROP FOREIGN KEY `fk_referee_country_id`');
        $this->addSql('ALTER TABLE referee DROP FOREIGN KEY `fk_referee_person_id`');
        $this->addSql('ALTER TABLE referee CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE person_id person_id INT DEFAULT NULL, CHANGE country_id country_id INT DEFAULT NULL, CHANGE level level VARCHAR(50) DEFAULT NULL');
        $this->addSql('ALTER TABLE referee ADD CONSTRAINT FK_D60FB342217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE referee ADD CONSTRAINT FK_D60FB342F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE referee RENAME INDEX fk_referee_person_id TO IDX_D60FB342217BBB47');
        $this->addSql('ALTER TABLE referee RENAME INDEX fk_referee_country_id TO IDX_D60FB342F92F3E70');
        $this->addSql('ALTER TABLE region DROP FOREIGN KEY `fk_region_country_id`');
        $this->addSql('ALTER TABLE region CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE country_id country_id INT DEFAULT NULL, CHANGE name name VARCHAR(150) DEFAULT NULL, CHANGE type type VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE region ADD CONSTRAINT FK_F62F176F92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE region RENAME INDEX fk_region_country_id TO IDX_F62F176F92F3E70');
        $this->addSql('ALTER TABLE scoresheet DROP FOREIGN KEY `fk_scoresheet_coach_id`');
        $this->addSql('ALTER TABLE scoresheet DROP FOREIGN KEY `fk_scoresheet_fixture_id`');
        $this->addSql('ALTER TABLE scoresheet CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE fixture_id fixture_id INT DEFAULT NULL, CHANGE attendance attendance INT DEFAULT NULL, CHANGE fixed_time fixed_time VARCHAR(5) DEFAULT NULL, CHANGE kickoff_time kickoff_time VARCHAR(5) DEFAULT NULL, CHANGE half_time half_time VARCHAR(5) DEFAULT NULL, CHANGE second_half_start second_half_start VARCHAR(5) DEFAULT NULL, CHANGE full_time full_time VARCHAR(5) DEFAULT NULL, CHANGE stoppage_time stoppage_time VARCHAR(5) DEFAULT NULL, CHANGE match_stop_time match_stop_time VARCHAR(5) DEFAULT NULL, CHANGE reservations reservations LONGTEXT DEFAULT NULL, CHANGE report report LONGTEXT DEFAULT NULL, CHANGE signed_place signed_place VARCHAR(150) DEFAULT NULL, CHANGE signed_on signed_on DATE DEFAULT NULL, CHANGE coach_id coach_id INT DEFAULT NULL, CHANGE form_state form_state VARCHAR(1) DEFAULT NULL');
        $this->addSql('ALTER TABLE scoresheet ADD CONSTRAINT FK_F001608FE524616D FOREIGN KEY (fixture_id) REFERENCES fixture (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE scoresheet ADD CONSTRAINT FK_F001608F3C105691 FOREIGN KEY (coach_id) REFERENCES person (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE scoresheet RENAME INDEX fk_scoresheet_coach_id TO IDX_F001608F3C105691');
        $this->addSql('ALTER TABLE scoresheet_lineup DROP FOREIGN KEY `fk_scoresheet_lineup_player_id`');
        $this->addSql('ALTER TABLE scoresheet_lineup DROP FOREIGN KEY `fk_scoresheet_lineup_position_id`');
        $this->addSql('ALTER TABLE scoresheet_lineup DROP FOREIGN KEY `fk_scoresheet_lineup_scoresheet_id`');
        $this->addSql('ALTER TABLE scoresheet_lineup DROP FOREIGN KEY `fk_scoresheet_lineup_team_id`');
        $this->addSql('ALTER TABLE scoresheet_lineup CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE scoresheet_id scoresheet_id INT DEFAULT NULL, CHANGE team_id team_id INT DEFAULT NULL, CHANGE player_id player_id INT DEFAULT NULL, CHANGE player_name_text player_name_text VARCHAR(200) DEFAULT NULL, CHANGE shirt_number shirt_number INT DEFAULT NULL, CHANGE lineup_role lineup_role VARCHAR(12) DEFAULT NULL, CHANGE is_captain is_captain TINYINT DEFAULT NULL, CHANGE position_id position_id INT DEFAULT NULL, CHANGE sort_order sort_order INT DEFAULT NULL');
        $this->addSql('ALTER TABLE scoresheet_lineup ADD CONSTRAINT FK_F9E1431F9ED2C24C FOREIGN KEY (scoresheet_id) REFERENCES scoresheet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE scoresheet_lineup ADD CONSTRAINT FK_F9E1431F296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE scoresheet_lineup ADD CONSTRAINT FK_F9E1431F99E6F5DF FOREIGN KEY (player_id) REFERENCES player (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE scoresheet_lineup ADD CONSTRAINT FK_F9E1431FDD842E46 FOREIGN KEY (position_id) REFERENCES position (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE scoresheet_lineup RENAME INDEX fk_scoresheet_lineup_team_id TO IDX_F9E1431F296CD8AE');
        $this->addSql('ALTER TABLE scoresheet_lineup RENAME INDEX fk_scoresheet_lineup_position_id TO IDX_F9E1431FDD842E46');
        $this->addSql('ALTER TABLE scoresheet_official DROP FOREIGN KEY `fk_scoresheet_official_person_id`');
        $this->addSql('ALTER TABLE scoresheet_official DROP FOREIGN KEY `fk_scoresheet_official_scoresheet_id`');
        $this->addSql('ALTER TABLE scoresheet_official CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE scoresheet_id scoresheet_id INT DEFAULT NULL, CHANGE role role VARCHAR(30) DEFAULT NULL, CHANGE person_id person_id INT DEFAULT NULL, CHANGE name_text name_text VARCHAR(150) DEFAULT NULL');
        $this->addSql('ALTER TABLE scoresheet_official ADD CONSTRAINT FK_6C550AE59ED2C24C FOREIGN KEY (scoresheet_id) REFERENCES scoresheet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE scoresheet_official ADD CONSTRAINT FK_6C550AE5217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE scoresheet_official RENAME INDEX fk_scoresheet_official_scoresheet_id TO IDX_6C550AE59ED2C24C');
        $this->addSql('ALTER TABLE scoresheet_official RENAME INDEX fk_scoresheet_official_person_id TO IDX_6C550AE5217BBB47');
        $this->addSql('ALTER TABLE scoresheet_substitution DROP FOREIGN KEY `fk_scoresheet_substitution_player_in_id`');
        $this->addSql('ALTER TABLE scoresheet_substitution DROP FOREIGN KEY `fk_scoresheet_substitution_player_out_id`');
        $this->addSql('ALTER TABLE scoresheet_substitution DROP FOREIGN KEY `fk_scoresheet_substitution_scoresheet_id`');
        $this->addSql('ALTER TABLE scoresheet_substitution DROP FOREIGN KEY `fk_scoresheet_substitution_team_id`');
        $this->addSql('ALTER TABLE scoresheet_substitution CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE scoresheet_id scoresheet_id INT DEFAULT NULL, CHANGE team_id team_id INT DEFAULT NULL, CHANGE player_out_id player_out_id INT DEFAULT NULL, CHANGE player_in_id player_in_id INT DEFAULT NULL, CHANGE player_out_text player_out_text VARCHAR(200) DEFAULT NULL, CHANGE player_in_text player_in_text VARCHAR(200) DEFAULT NULL, CHANGE minute minute VARCHAR(8) DEFAULT NULL');
        $this->addSql('ALTER TABLE scoresheet_substitution ADD CONSTRAINT FK_E318A73A9ED2C24C FOREIGN KEY (scoresheet_id) REFERENCES scoresheet (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE scoresheet_substitution ADD CONSTRAINT FK_E318A73A296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE scoresheet_substitution ADD CONSTRAINT FK_E318A73A9B0FCEA4 FOREIGN KEY (player_out_id) REFERENCES player (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE scoresheet_substitution ADD CONSTRAINT FK_E318A73AAF8B0575 FOREIGN KEY (player_in_id) REFERENCES player (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE scoresheet_substitution RENAME INDEX fk_scoresheet_substitution_scoresheet_id TO IDX_E318A73A9ED2C24C');
        $this->addSql('ALTER TABLE scoresheet_substitution RENAME INDEX fk_scoresheet_substitution_team_id TO IDX_E318A73A296CD8AE');
        $this->addSql('ALTER TABLE scoresheet_substitution RENAME INDEX fk_scoresheet_substitution_player_out_id TO IDX_E318A73A9B0FCEA4');
        $this->addSql('ALTER TABLE scoresheet_substitution RENAME INDEX fk_scoresheet_substitution_player_in_id TO IDX_E318A73AAF8B0575');
        $this->addSql('ALTER TABLE season CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(20) DEFAULT NULL, CHANGE year_start year_start INT DEFAULT NULL, CHANGE year_end year_end INT DEFAULT NULL');
        $this->addSql('ALTER TABLE source_file CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE filename filename VARCHAR(255) DEFAULT NULL, CHANGE checksum_sha1 checksum_sha1 VARCHAR(40) DEFAULT NULL, CHANGE imported_at imported_at DATETIME DEFAULT NULL, CHANGE note note VARCHAR(255) DEFAULT NULL');
        $this->addSql('ALTER TABLE stadium DROP FOREIGN KEY `fk_stadium_city_id`');
        $this->addSql('ALTER TABLE stadium DROP FOREIGN KEY `fk_stadium_country_id`');
        $this->addSql('ALTER TABLE stadium CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(200) DEFAULT NULL, CHANGE city_id city_id INT DEFAULT NULL, CHANGE country_id country_id INT DEFAULT NULL, CHANGE capacity capacity INT DEFAULT NULL');
        $this->addSql('ALTER TABLE stadium ADD CONSTRAINT FK_E604044F8BAC62AF FOREIGN KEY (city_id) REFERENCES city (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE stadium ADD CONSTRAINT FK_E604044FF92F3E70 FOREIGN KEY (country_id) REFERENCES country (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE stadium RENAME INDEX fk_stadium_city_id TO IDX_E604044F8BAC62AF');
        $this->addSql('ALTER TABLE stadium RENAME INDEX fk_stadium_country_id TO IDX_E604044FF92F3E70');
        $this->addSql('ALTER TABLE stage DROP FOREIGN KEY `fk_stage_edition_id`');
        $this->addSql('ALTER TABLE stage CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE edition_id edition_id INT DEFAULT NULL, CHANGE name name VARCHAR(120) DEFAULT NULL, CHANGE stage_type stage_type VARCHAR(30) DEFAULT NULL, CHANGE is_final is_final TINYINT DEFAULT NULL, CHANGE sort_order sort_order INT DEFAULT NULL');
        $this->addSql('ALTER TABLE stage ADD CONSTRAINT FK_C27C936974281A5E FOREIGN KEY (edition_id) REFERENCES edition (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stage RENAME INDEX fk_stage_edition_id TO IDX_C27C936974281A5E');
        $this->addSql('ALTER TABLE standing DROP FOREIGN KEY `fk_standing_edition_id`');
        $this->addSql('ALTER TABLE standing DROP FOREIGN KEY `fk_standing_matchday_id`');
        $this->addSql('ALTER TABLE standing DROP FOREIGN KEY `fk_standing_stage_id`');
        $this->addSql('ALTER TABLE standing DROP FOREIGN KEY `fk_standing_team_id`');
        $this->addSql('ALTER TABLE standing CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE edition_id edition_id INT DEFAULT NULL, CHANGE stage_id stage_id INT DEFAULT NULL, CHANGE matchday_id matchday_id INT DEFAULT NULL, CHANGE team_id team_id INT DEFAULT NULL, CHANGE rank rank INT DEFAULT NULL, CHANGE played played INT DEFAULT NULL, CHANGE won won INT DEFAULT NULL, CHANGE draw draw INT DEFAULT NULL, CHANGE lost lost INT DEFAULT NULL, CHANGE goals_for goals_for INT DEFAULT NULL, CHANGE goals_against goals_against INT DEFAULT NULL, CHANGE goal_diff goal_diff INT DEFAULT NULL, CHANGE points points INT DEFAULT NULL, CHANGE observation observation VARCHAR(200) DEFAULT NULL, CHANGE source_note source_note VARCHAR(200) DEFAULT NULL');
        $this->addSql('ALTER TABLE standing ADD CONSTRAINT FK_619A8AD874281A5E FOREIGN KEY (edition_id) REFERENCES edition (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE standing ADD CONSTRAINT FK_619A8AD82298D193 FOREIGN KEY (stage_id) REFERENCES stage (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE standing ADD CONSTRAINT FK_619A8AD83D90D21B FOREIGN KEY (matchday_id) REFERENCES matchday (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE standing ADD CONSTRAINT FK_619A8AD8296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE standing RENAME INDEX fk_standing_stage_id TO IDX_619A8AD82298D193');
        $this->addSql('ALTER TABLE standing RENAME INDEX fk_standing_matchday_id TO IDX_619A8AD83D90D21B');
        $this->addSql('ALTER TABLE team DROP FOREIGN KEY `fk_team_club_id`');
        $this->addSql('ALTER TABLE team DROP FOREIGN KEY `fk_team_national_team_id`');
        $this->addSql('ALTER TABLE team CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE team_type team_type VARCHAR(10) DEFAULT NULL, CHANGE club_id club_id INT DEFAULT NULL, CHANGE national_team_id national_team_id INT DEFAULT NULL, CHANGE display_name display_name VARCHAR(200) DEFAULT NULL');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61F61190A32 FOREIGN KEY (club_id) REFERENCES club (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT FK_C4E0A61F9008F799 FOREIGN KEY (national_team_id) REFERENCES national_team (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE team RENAME INDEX fk_team_club_id TO IDX_C4E0A61F61190A32');
        $this->addSql('ALTER TABLE team RENAME INDEX fk_team_national_team_id TO IDX_C4E0A61F9008F799');
        $this->addSql('ALTER TABLE trophy DROP FOREIGN KEY `fk_trophy_competition_id`');
        $this->addSql('ALTER TABLE trophy CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE name name VARCHAR(200) DEFAULT NULL, CHANGE competition_id competition_id INT DEFAULT NULL, CHANGE trophy_type trophy_type VARCHAR(30) DEFAULT NULL');
        $this->addSql('ALTER TABLE trophy ADD CONSTRAINT FK_112AFAE97B39D312 FOREIGN KEY (competition_id) REFERENCES competition (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE trophy RENAME INDEX fk_trophy_competition_id TO IDX_112AFAE97B39D312');
        $this->addSql('ALTER TABLE trophy_award DROP FOREIGN KEY `fk_trophy_award_edition_id`');
        $this->addSql('ALTER TABLE trophy_award DROP FOREIGN KEY `fk_trophy_award_person_id`');
        $this->addSql('ALTER TABLE trophy_award DROP FOREIGN KEY `fk_trophy_award_season_id`');
        $this->addSql('ALTER TABLE trophy_award DROP FOREIGN KEY `fk_trophy_award_team_id`');
        $this->addSql('ALTER TABLE trophy_award DROP FOREIGN KEY `fk_trophy_award_trophy_id`');
        $this->addSql('ALTER TABLE trophy_award CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE trophy_id trophy_id INT DEFAULT NULL, CHANGE season_id season_id INT DEFAULT NULL, CHANGE edition_id edition_id INT DEFAULT NULL, CHANGE team_id team_id INT DEFAULT NULL, CHANGE person_id person_id INT DEFAULT NULL, CHANGE rank rank INT DEFAULT NULL, CHANGE note note VARCHAR(200) DEFAULT NULL');
        $this->addSql('ALTER TABLE trophy_award ADD CONSTRAINT FK_E1C746D0F59AEEEF FOREIGN KEY (trophy_id) REFERENCES trophy (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trophy_award ADD CONSTRAINT FK_E1C746D04EC001D1 FOREIGN KEY (season_id) REFERENCES season (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE trophy_award ADD CONSTRAINT FK_E1C746D074281A5E FOREIGN KEY (edition_id) REFERENCES edition (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE trophy_award ADD CONSTRAINT FK_E1C746D0296CD8AE FOREIGN KEY (team_id) REFERENCES team (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE trophy_award ADD CONSTRAINT FK_E1C746D0217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE trophy_award RENAME INDEX fk_trophy_award_trophy_id TO IDX_E1C746D0F59AEEEF');
        $this->addSql('ALTER TABLE trophy_award RENAME INDEX fk_trophy_award_edition_id TO IDX_E1C746D074281A5E');
        $this->addSql('ALTER TABLE trophy_award_person DROP FOREIGN KEY `fk_trophy_award_person_person_id`');
        $this->addSql('ALTER TABLE trophy_award_person DROP FOREIGN KEY `fk_trophy_award_person_trophy_award_id`');
        $this->addSql('ALTER TABLE trophy_award_person CHANGE id id INT AUTO_INCREMENT NOT NULL, CHANGE trophy_award_id trophy_award_id INT DEFAULT NULL, CHANGE person_id person_id INT DEFAULT NULL, CHANGE role role VARCHAR(20) DEFAULT NULL');
        $this->addSql('ALTER TABLE trophy_award_person ADD CONSTRAINT FK_8ADBCE5748EB4F71 FOREIGN KEY (trophy_award_id) REFERENCES trophy_award (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trophy_award_person ADD CONSTRAINT FK_8ADBCE57217BBB47 FOREIGN KEY (person_id) REFERENCES person (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE trophy_award_person RENAME INDEX fk_trophy_award_person_trophy_award_id TO IDX_8ADBCE5748EB4F71');
        $this->addSql('ALTER TABLE trophy_award_person RENAME INDEX fk_trophy_award_person_person_id TO IDX_8ADBCE57217BBB47');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE category CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE name name VARCHAR(120) DEFAULT NULL COMMENT \'Category (Seniors, U23, Women...)\', CHANGE gender gender VARCHAR(10) DEFAULT NULL COMMENT \'M/F/Mixed\', CHANGE age_min age_min INT DEFAULT NULL COMMENT \'Min age\', CHANGE age_max age_max INT DEFAULT NULL COMMENT \'Max age\'');
        $this->addSql('ALTER TABLE city DROP FOREIGN KEY FK_2D5B0234F92F3E70');
        $this->addSql('ALTER TABLE city DROP FOREIGN KEY FK_2D5B023498260155');
        $this->addSql('ALTER TABLE city CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE name name VARCHAR(150) DEFAULT NULL COMMENT \'City\', CHANGE country_id country_id INT DEFAULT NULL COMMENT \'FK country\', CHANGE region_id region_id INT DEFAULT NULL COMMENT \'FK region\'');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT `fk_city_country_id` FOREIGN KEY (country_id) REFERENCES country (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE city ADD CONSTRAINT `fk_city_region_id` FOREIGN KEY (region_id) REFERENCES region (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE city RENAME INDEX idx_2d5b0234f92f3e70 TO fk_city_country_id');
        $this->addSql('ALTER TABLE city RENAME INDEX idx_2d5b023498260155 TO fk_city_region_id');
        $this->addSql('ALTER TABLE club DROP FOREIGN KEY FK_B8EE3872F92F3E70');
        $this->addSql('ALTER TABLE club DROP FOREIGN KEY FK_B8EE38728BAC62AF');
        $this->addSql('ALTER TABLE club DROP FOREIGN KEY FK_B8EE387298260155');
        $this->addSql('ALTER TABLE club CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE name name VARCHAR(200) DEFAULT NULL COMMENT \'Club name\', CHANGE short_name short_name VARCHAR(80) DEFAULT NULL COMMENT \'Short name\', CHANGE founded_year founded_year INT DEFAULT NULL COMMENT \'Founded year\', CHANGE country_id country_id INT DEFAULT NULL COMMENT \'FK country\', CHANGE city_id city_id INT DEFAULT NULL COMMENT \'FK city\', CHANGE region_id region_id INT DEFAULT NULL COMMENT \'FK region/wilaya\'');
        $this->addSql('ALTER TABLE club ADD CONSTRAINT `fk_club_city_id` FOREIGN KEY (city_id) REFERENCES city (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE club ADD CONSTRAINT `fk_club_country_id` FOREIGN KEY (country_id) REFERENCES country (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE club ADD CONSTRAINT `fk_club_region_id` FOREIGN KEY (region_id) REFERENCES region (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE club RENAME INDEX idx_b8ee38728bac62af TO fk_club_city_id');
        $this->addSql('ALTER TABLE club RENAME INDEX idx_b8ee387298260155 TO fk_club_region_id');
        $this->addSql('ALTER TABLE club RENAME INDEX idx_b8ee3872f92f3e70 TO fk_club_country_id');
        $this->addSql('ALTER TABLE coach DROP FOREIGN KEY FK_3F596DCC217BBB47');
        $this->addSql('ALTER TABLE coach CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE role role VARCHAR(50) DEFAULT NULL COMMENT \'Head/Assistant/Trainer\', CHANGE person_id person_id INT DEFAULT NULL COMMENT \'FK person\'');
        $this->addSql('ALTER TABLE coach ADD CONSTRAINT `fk_coach_person_id` FOREIGN KEY (person_id) REFERENCES person (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE coach RENAME INDEX idx_3f596dcc217bbb47 TO fk_coach_person_id');
        $this->addSql('ALTER TABLE competition DROP FOREIGN KEY FK_B50A2CB112469DE2');
        $this->addSql('ALTER TABLE competition CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE name name VARCHAR(200) DEFAULT NULL COMMENT \'Competition name\', CHANGE type type VARCHAR(30) DEFAULT NULL COMMENT \'league/cup/friendly/qualifier\', CHANGE organizer organizer VARCHAR(120) DEFAULT NULL COMMENT \'FAF/CAF/FIFA/UEFA/etc\', CHANGE category_id category_id INT DEFAULT NULL COMMENT \'FK category\'');
        $this->addSql('ALTER TABLE competition ADD CONSTRAINT `fk_competition_category_id` FOREIGN KEY (category_id) REFERENCES category (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE competition RENAME INDEX idx_b50a2cb112469de2 TO fk_competition_category_id');
        $this->addSql('ALTER TABLE country CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE name name VARCHAR(150) DEFAULT NULL COMMENT \'Country name\', CHANGE iso2 iso2 VARCHAR(2) DEFAULT NULL COMMENT \'ISO 3166-1 alpha-2\', CHANGE iso3 iso3 VARCHAR(3) DEFAULT NULL COMMENT \'ISO 3166-1 alpha-3\', CHANGE fifa_code fifa_code VARCHAR(3) DEFAULT NULL COMMENT \'FIFA code\'');
        $this->addSql('ALTER TABLE division DROP FOREIGN KEY FK_10174714F92F3E70');
        $this->addSql('ALTER TABLE division CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE name name VARCHAR(120) DEFAULT NULL COMMENT \'Division name\', CHANGE level level INT DEFAULT NULL COMMENT \'1=top\', CHANGE in_championship in_championship TINYINT DEFAULT NULL COMMENT \'Part of league system\', CHANGE country_id country_id INT DEFAULT NULL COMMENT \'FK country\'');
        $this->addSql('ALTER TABLE division ADD CONSTRAINT `fk_division_country_id` FOREIGN KEY (country_id) REFERENCES country (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE division RENAME INDEX idx_10174714f92f3e70 TO fk_division_country_id');
        $this->addSql('ALTER TABLE edition DROP FOREIGN KEY FK_A891181F7B39D312');
        $this->addSql('ALTER TABLE edition DROP FOREIGN KEY FK_A891181F4EC001D1');
        $this->addSql('ALTER TABLE edition DROP FOREIGN KEY FK_A891181F41859289');
        $this->addSql('ALTER TABLE edition CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE name name VARCHAR(120) DEFAULT NULL COMMENT \'Edition name\', CHANGE competition_id competition_id INT DEFAULT NULL COMMENT \'FK competition\', CHANGE season_id season_id INT DEFAULT NULL COMMENT \'FK season\', CHANGE division_id division_id INT DEFAULT NULL COMMENT \'FK division (optional)\'');
        $this->addSql('ALTER TABLE edition ADD CONSTRAINT `fk_edition_competition_id` FOREIGN KEY (competition_id) REFERENCES competition (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE edition ADD CONSTRAINT `fk_edition_division_id` FOREIGN KEY (division_id) REFERENCES division (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE edition ADD CONSTRAINT `fk_edition_season_id` FOREIGN KEY (season_id) REFERENCES season (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE edition RENAME INDEX idx_a891181f41859289 TO fk_edition_division_id');
        $this->addSql('ALTER TABLE edition RENAME INDEX idx_a891181f4ec001d1 TO fk_edition_season_id');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY FK_5E540EE7B39D312');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY FK_5E540EE4EC001D1');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY FK_5E540EE74281A5E');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY FK_5E540EE2298D193');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY FK_5E540EE3D90D21B');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY FK_5E540EE41859289');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY FK_5E540EE12469DE2');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY FK_5E540EE7E860E36');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY FK_5E540EE8BAC62AF');
        $this->addSql('ALTER TABLE fixture DROP FOREIGN KEY FK_5E540EEF92F3E70');
        $this->addSql('ALTER TABLE fixture CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE external_match_no external_match_no INT DEFAULT NULL COMMENT \'N° du match (source)\', CHANGE match_date match_date DATE DEFAULT NULL COMMENT \'Match date\', CHANGE played played TINYINT DEFAULT NULL COMMENT \'Played\', CHANGE is_official is_official TINYINT DEFAULT NULL COMMENT \'Official match\', CHANGE notes notes TEXT DEFAULT NULL COMMENT \'Notes\', CHANGE competition_id competition_id INT DEFAULT NULL COMMENT \'FK competition\', CHANGE season_id season_id INT DEFAULT NULL COMMENT \'FK season\', CHANGE edition_id edition_id INT DEFAULT NULL COMMENT \'FK edition\', CHANGE stage_id stage_id INT DEFAULT NULL COMMENT \'FK stage\', CHANGE matchday_id matchday_id INT DEFAULT NULL COMMENT \'FK matchday\', CHANGE division_id division_id INT DEFAULT NULL COMMENT \'FK division\', CHANGE category_id category_id INT DEFAULT NULL COMMENT \'FK category\', CHANGE stadium_id stadium_id INT DEFAULT NULL COMMENT \'FK stadium\', CHANGE city_id city_id INT DEFAULT NULL COMMENT \'FK city\', CHANGE country_id country_id INT DEFAULT NULL COMMENT \'FK country (venue)\'');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT `fk_fixture_category_id` FOREIGN KEY (category_id) REFERENCES category (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT `fk_fixture_city_id` FOREIGN KEY (city_id) REFERENCES city (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT `fk_fixture_competition_id` FOREIGN KEY (competition_id) REFERENCES competition (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT `fk_fixture_country_id` FOREIGN KEY (country_id) REFERENCES country (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT `fk_fixture_division_id` FOREIGN KEY (division_id) REFERENCES division (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT `fk_fixture_edition_id` FOREIGN KEY (edition_id) REFERENCES edition (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT `fk_fixture_matchday_id` FOREIGN KEY (matchday_id) REFERENCES matchday (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT `fk_fixture_season_id` FOREIGN KEY (season_id) REFERENCES season (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT `fk_fixture_stadium_id` FOREIGN KEY (stadium_id) REFERENCES stadium (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture ADD CONSTRAINT `fk_fixture_stage_id` FOREIGN KEY (stage_id) REFERENCES stage (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE fixture RENAME INDEX idx_5e540ee7e860e36 TO fk_fixture_stadium_id');
        $this->addSql('ALTER TABLE fixture RENAME INDEX idx_5e540ee3d90d21b TO fk_fixture_matchday_id');
        $this->addSql('ALTER TABLE fixture RENAME INDEX idx_5e540ee8bac62af TO fk_fixture_city_id');
        $this->addSql('ALTER TABLE fixture RENAME INDEX idx_5e540ee41859289 TO fk_fixture_division_id');
        $this->addSql('ALTER TABLE fixture RENAME INDEX idx_5e540eef92f3e70 TO fk_fixture_country_id');
        $this->addSql('ALTER TABLE fixture RENAME INDEX idx_5e540ee12469de2 TO fk_fixture_category_id');
        $this->addSql('ALTER TABLE fixture_participant DROP FOREIGN KEY FK_6592938CE524616D');
        $this->addSql('ALTER TABLE fixture_participant DROP FOREIGN KEY FK_6592938C296CD8AE');
        $this->addSql('ALTER TABLE fixture_participant CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE role role VARCHAR(1) DEFAULT NULL COMMENT \'A or B (from source)\', CHANGE score score INT DEFAULT NULL COMMENT \'Goals in regular time\', CHANGE score_extra score_extra INT DEFAULT NULL COMMENT \'Extra time goals (optional)\', CHANGE score_penalty score_penalty INT DEFAULT NULL COMMENT \'Penalty shootout goals (optional)\', CHANGE is_winner is_winner TINYINT DEFAULT NULL COMMENT \'Winner\', CHANGE venue_role venue_role VARCHAR(10) DEFAULT NULL COMMENT \'HOME/AWAY/NEUTRAL/UNKNOWN (derived)\', CHANGE fixture_id fixture_id INT DEFAULT NULL COMMENT \'FK fixture\', CHANGE team_id team_id INT DEFAULT NULL COMMENT \'FK team\'');
        $this->addSql('ALTER TABLE fixture_participant ADD CONSTRAINT `fk_fixture_participant_fixture_id` FOREIGN KEY (fixture_id) REFERENCES fixture (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE fixture_participant ADD CONSTRAINT `fk_fixture_participant_team_id` FOREIGN KEY (team_id) REFERENCES team (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE import_batch DROP FOREIGN KEY FK_155EFD1ADA14C104');
        $this->addSql('ALTER TABLE import_batch CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE entity entity VARCHAR(50) DEFAULT NULL COMMENT \'fixture/scoresheet/player...\', CHANGE status status VARCHAR(20) DEFAULT NULL COMMENT \'started/done/failed\', CHANGE inserted inserted INT DEFAULT NULL COMMENT \'Inserted\', CHANGE updated updated INT DEFAULT NULL COMMENT \'Updated\', CHANGE skipped skipped INT DEFAULT NULL COMMENT \'Skipped\', CHANGE started_at started_at DATETIME DEFAULT NULL COMMENT \'Started\', CHANGE finished_at finished_at DATETIME DEFAULT NULL COMMENT \'Finished\', CHANGE error error TEXT DEFAULT NULL COMMENT \'Error\', CHANGE source_file_id source_file_id INT DEFAULT NULL COMMENT \'FK source_file\'');
        $this->addSql('ALTER TABLE import_batch ADD CONSTRAINT `fk_import_batch_source_file_id` FOREIGN KEY (source_file_id) REFERENCES source_file (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE import_batch RENAME INDEX idx_155efd1ada14c104 TO fk_import_batch_source_file_id');
        $this->addSql('ALTER TABLE matchday DROP FOREIGN KEY FK_A95F407674281A5E');
        $this->addSql('ALTER TABLE matchday CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE label label VARCHAR(50) DEFAULT NULL COMMENT \'Journée/Matchday label (J1...)\', CHANGE number number INT DEFAULT NULL COMMENT \'Matchday number\', CHANGE start_date start_date DATE DEFAULT NULL COMMENT \'Optional\', CHANGE end_date end_date DATE DEFAULT NULL COMMENT \'Optional\', CHANGE edition_id edition_id INT DEFAULT NULL COMMENT \'FK edition\'');
        $this->addSql('ALTER TABLE matchday ADD CONSTRAINT `fk_matchday_edition_id` FOREIGN KEY (edition_id) REFERENCES edition (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE match_card DROP FOREIGN KEY FK_777B29A1E524616D');
        $this->addSql('ALTER TABLE match_card DROP FOREIGN KEY FK_777B29A1296CD8AE');
        $this->addSql('ALTER TABLE match_card DROP FOREIGN KEY FK_777B29A199E6F5DF');
        $this->addSql('ALTER TABLE match_card CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE player_text player_text VARCHAR(200) DEFAULT NULL COMMENT \'Fallback\', CHANGE minute minute VARCHAR(8) DEFAULT NULL COMMENT \'Minute\', CHANGE card_type card_type VARCHAR(5) DEFAULT NULL COMMENT \'Y/R/Y2\', CHANGE reason reason VARCHAR(200) DEFAULT NULL COMMENT \'Reason\', CHANGE fixture_id fixture_id INT DEFAULT NULL COMMENT \'FK fixture\', CHANGE team_id team_id INT DEFAULT NULL COMMENT \'FK team\', CHANGE player_id player_id INT DEFAULT NULL COMMENT \'FK player\'');
        $this->addSql('ALTER TABLE match_card ADD CONSTRAINT `fk_match_card_fixture_id` FOREIGN KEY (fixture_id) REFERENCES fixture (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE match_card ADD CONSTRAINT `fk_match_card_player_id` FOREIGN KEY (player_id) REFERENCES player (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE match_card ADD CONSTRAINT `fk_match_card_team_id` FOREIGN KEY (team_id) REFERENCES team (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE match_card RENAME INDEX idx_777b29a1e524616d TO fk_match_card_fixture_id');
        $this->addSql('ALTER TABLE match_card RENAME INDEX idx_777b29a1296cd8ae TO fk_match_card_team_id');
        $this->addSql('ALTER TABLE match_card RENAME INDEX idx_777b29a199e6f5df TO fk_match_card_player_id');
        $this->addSql('ALTER TABLE match_goal DROP FOREIGN KEY FK_9DB35A5CE524616D');
        $this->addSql('ALTER TABLE match_goal DROP FOREIGN KEY FK_9DB35A5C296CD8AE');
        $this->addSql('ALTER TABLE match_goal DROP FOREIGN KEY FK_9DB35A5C43B35028');
        $this->addSql('ALTER TABLE match_goal CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE scorer_text scorer_text VARCHAR(200) DEFAULT NULL COMMENT \'Fallback\', CHANGE minute minute VARCHAR(8) DEFAULT NULL COMMENT \'Minute\', CHANGE goal_type goal_type VARCHAR(20) DEFAULT NULL COMMENT \'normal/penalty/own_goal\', CHANGE fixture_id fixture_id INT DEFAULT NULL COMMENT \'FK fixture\', CHANGE team_id team_id INT DEFAULT NULL COMMENT \'FK team\', CHANGE scorer_id scorer_id INT DEFAULT NULL COMMENT \'FK player\'');
        $this->addSql('ALTER TABLE match_goal ADD CONSTRAINT `fk_match_goal_fixture_id` FOREIGN KEY (fixture_id) REFERENCES fixture (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE match_goal ADD CONSTRAINT `fk_match_goal_scorer_id` FOREIGN KEY (scorer_id) REFERENCES player (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE match_goal ADD CONSTRAINT `fk_match_goal_team_id` FOREIGN KEY (team_id) REFERENCES team (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE match_goal RENAME INDEX idx_9db35a5c296cd8ae TO fk_match_goal_team_id');
        $this->addSql('ALTER TABLE name_alias CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE entity_type entity_type VARCHAR(30) DEFAULT NULL COMMENT \'team/club/stadium/competition/person/city\', CHANGE entity_id entity_id INT DEFAULT NULL COMMENT \'Target id\', CHANGE alias alias VARCHAR(200) DEFAULT NULL COMMENT \'Alias (source)\', CHANGE normalized normalized VARCHAR(200) DEFAULT NULL COMMENT \'Normalized key\'');
        $this->addSql('ALTER TABLE national_team DROP FOREIGN KEY FK_6034EB55F92F3E70');
        $this->addSql('ALTER TABLE national_team DROP FOREIGN KEY FK_6034EB5512469DE2');
        $this->addSql('ALTER TABLE national_team CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE name name VARCHAR(200) DEFAULT NULL COMMENT \'Team name\', CHANGE country_id country_id INT DEFAULT NULL COMMENT \'FK country\', CHANGE category_id category_id INT DEFAULT NULL COMMENT \'FK category\'');
        $this->addSql('ALTER TABLE national_team ADD CONSTRAINT `fk_national_team_category_id` FOREIGN KEY (category_id) REFERENCES category (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE national_team ADD CONSTRAINT `fk_national_team_country_id` FOREIGN KEY (country_id) REFERENCES country (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE national_team RENAME INDEX idx_6034eb5512469de2 TO fk_national_team_category_id');
        $this->addSql('ALTER TABLE national_team RENAME INDEX idx_6034eb55f92f3e70 TO fk_national_team_country_id');
        $this->addSql('ALTER TABLE person DROP FOREIGN KEY FK_34DCD176F0B1CED9');
        $this->addSql('ALTER TABLE person DROP FOREIGN KEY FK_34DCD1763E234BFB');
        $this->addSql('ALTER TABLE person DROP FOREIGN KEY FK_34DCD176C8E7B5D5');
        $this->addSql('ALTER TABLE person DROP FOREIGN KEY FK_34DCD1764A08B118');
        $this->addSql('ALTER TABLE person CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE full_name full_name VARCHAR(200) DEFAULT NULL COMMENT \'Name\', CHANGE birth_date birth_date DATE DEFAULT NULL COMMENT \'Birth date\', CHANGE birth_city_id birth_city_id INT DEFAULT NULL COMMENT \'FK city\', CHANGE birth_region_id birth_region_id INT DEFAULT NULL COMMENT \'FK region\', CHANGE birth_country_id birth_country_id INT DEFAULT NULL COMMENT \'FK country\', CHANGE nationality_country_id nationality_country_id INT DEFAULT NULL COMMENT \'FK country\'');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT `fk_person_birth_city_id` FOREIGN KEY (birth_city_id) REFERENCES city (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT `fk_person_birth_country_id` FOREIGN KEY (birth_country_id) REFERENCES country (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT `fk_person_birth_region_id` FOREIGN KEY (birth_region_id) REFERENCES region (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE person ADD CONSTRAINT `fk_person_nationality_country_id` FOREIGN KEY (nationality_country_id) REFERENCES country (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE person RENAME INDEX idx_34dcd1763e234bfb TO fk_person_birth_region_id');
        $this->addSql('ALTER TABLE person RENAME INDEX idx_34dcd176c8e7b5d5 TO fk_person_birth_country_id');
        $this->addSql('ALTER TABLE person RENAME INDEX idx_34dcd1764a08b118 TO fk_person_nationality_country_id');
        $this->addSql('ALTER TABLE person RENAME INDEX idx_34dcd176f0b1ced9 TO fk_person_birth_city_id');
        $this->addSql('ALTER TABLE person_club_history DROP FOREIGN KEY FK_C9FC3584217BBB47');
        $this->addSql('ALTER TABLE person_club_history DROP FOREIGN KEY FK_C9FC358461190A32');
        $this->addSql('ALTER TABLE person_club_history CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE role role VARCHAR(20) DEFAULT NULL COMMENT \'PLAYER/COACH/STAFF\', CHANGE from_year from_year INT DEFAULT NULL COMMENT \'Optional\', CHANGE to_year to_year INT DEFAULT NULL COMMENT \'Optional\', CHANGE note note VARCHAR(200) DEFAULT NULL COMMENT \'Source/text\', CHANGE person_id person_id INT DEFAULT NULL COMMENT \'FK person\', CHANGE club_id club_id INT DEFAULT NULL COMMENT \'FK club\'');
        $this->addSql('ALTER TABLE person_club_history ADD CONSTRAINT `fk_person_club_history_club_id` FOREIGN KEY (club_id) REFERENCES club (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE person_club_history ADD CONSTRAINT `fk_person_club_history_person_id` FOREIGN KEY (person_id) REFERENCES person (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE person_club_history RENAME INDEX idx_c9fc358461190a32 TO fk_person_club_history_club_id');
        $this->addSql('ALTER TABLE person_club_history RENAME INDEX idx_c9fc3584217bbb47 TO fk_person_club_history_person_id');
        $this->addSql('ALTER TABLE player DROP FOREIGN KEY FK_98197A65217BBB47');
        $this->addSql('ALTER TABLE player DROP FOREIGN KEY FK_98197A65796B4EC7');
        $this->addSql('ALTER TABLE player CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE preferred_foot preferred_foot VARCHAR(10) DEFAULT NULL COMMENT \'L/R/Both\', CHANGE person_id person_id INT DEFAULT NULL COMMENT \'FK person\', CHANGE primary_position_id primary_position_id INT DEFAULT NULL COMMENT \'FK position\'');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT `fk_player_person_id` FOREIGN KEY (person_id) REFERENCES person (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE player ADD CONSTRAINT `fk_player_primary_position_id` FOREIGN KEY (primary_position_id) REFERENCES position (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE player RENAME INDEX idx_98197a65217bbb47 TO fk_player_person_id');
        $this->addSql('ALTER TABLE player RENAME INDEX idx_98197a65796b4ec7 TO fk_player_primary_position_id');
        $this->addSql('ALTER TABLE player_national_stats DROP FOREIGN KEY FK_D338C8099E6F5DF');
        $this->addSql('ALTER TABLE player_national_stats DROP FOREIGN KEY FK_D338C80296CD8AE');
        $this->addSql('ALTER TABLE player_national_stats CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE caps caps INT DEFAULT NULL COMMENT \'Caps\', CHANGE goals goals INT DEFAULT NULL COMMENT \'Goals\', CHANGE from_date from_date DATE DEFAULT NULL COMMENT \'Optional\', CHANGE to_date to_date DATE DEFAULT NULL COMMENT \'Optional\', CHANGE source_note source_note VARCHAR(200) DEFAULT NULL COMMENT \'Source\', CHANGE player_id player_id INT DEFAULT NULL COMMENT \'FK player\', CHANGE team_id team_id INT DEFAULT NULL COMMENT \'FK team (national)\'');
        $this->addSql('ALTER TABLE player_national_stats ADD CONSTRAINT `fk_player_national_stats_player_id` FOREIGN KEY (player_id) REFERENCES player (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE player_national_stats ADD CONSTRAINT `fk_player_national_stats_team_id` FOREIGN KEY (team_id) REFERENCES team (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE player_national_stats RENAME INDEX idx_d338c8099e6f5df TO fk_player_national_stats_player_id');
        $this->addSql('ALTER TABLE player_national_stats RENAME INDEX idx_d338c80296cd8ae TO fk_player_national_stats_team_id');
        $this->addSql('ALTER TABLE position CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE code code VARCHAR(10) DEFAULT NULL COMMENT \'GK/DF/MF/FW\', CHANGE label label VARCHAR(80) DEFAULT NULL COMMENT \'Position label\'');
        $this->addSql('ALTER TABLE referee DROP FOREIGN KEY FK_D60FB342217BBB47');
        $this->addSql('ALTER TABLE referee DROP FOREIGN KEY FK_D60FB342F92F3E70');
        $this->addSql('ALTER TABLE referee CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE level level VARCHAR(50) DEFAULT NULL COMMENT \'International/National\', CHANGE person_id person_id INT DEFAULT NULL COMMENT \'FK person\', CHANGE country_id country_id INT DEFAULT NULL COMMENT \'FK country\'');
        $this->addSql('ALTER TABLE referee ADD CONSTRAINT `fk_referee_country_id` FOREIGN KEY (country_id) REFERENCES country (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE referee ADD CONSTRAINT `fk_referee_person_id` FOREIGN KEY (person_id) REFERENCES person (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE referee RENAME INDEX idx_d60fb342217bbb47 TO fk_referee_person_id');
        $this->addSql('ALTER TABLE referee RENAME INDEX idx_d60fb342f92f3e70 TO fk_referee_country_id');
        $this->addSql('ALTER TABLE region DROP FOREIGN KEY FK_F62F176F92F3E70');
        $this->addSql('ALTER TABLE region CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE name name VARCHAR(150) DEFAULT NULL COMMENT \'Region/Wilaya/State\', CHANGE type type VARCHAR(30) DEFAULT NULL COMMENT \'wilaya/region/state/province\', CHANGE country_id country_id INT DEFAULT NULL COMMENT \'FK country\'');
        $this->addSql('ALTER TABLE region ADD CONSTRAINT `fk_region_country_id` FOREIGN KEY (country_id) REFERENCES country (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE region RENAME INDEX idx_f62f176f92f3e70 TO fk_region_country_id');
        $this->addSql('ALTER TABLE scoresheet DROP FOREIGN KEY FK_F001608FE524616D');
        $this->addSql('ALTER TABLE scoresheet DROP FOREIGN KEY FK_F001608F3C105691');
        $this->addSql('ALTER TABLE scoresheet CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE attendance attendance INT DEFAULT NULL COMMENT \'Attendance\', CHANGE fixed_time fixed_time VARCHAR(5) DEFAULT NULL COMMENT \'Scheduled time HH:MM\', CHANGE kickoff_time kickoff_time VARCHAR(5) DEFAULT NULL COMMENT \'Kick-off time HH:MM\', CHANGE half_time half_time VARCHAR(5) DEFAULT NULL COMMENT \'Half-time HH:MM\', CHANGE second_half_start second_half_start VARCHAR(5) DEFAULT NULL COMMENT \'Second half start HH:MM\', CHANGE full_time full_time VARCHAR(5) DEFAULT NULL COMMENT \'Full time HH:MM\', CHANGE stoppage_time stoppage_time VARCHAR(5) DEFAULT NULL COMMENT \'Stoppage time HH:MM\', CHANGE match_stop_time match_stop_time VARCHAR(5) DEFAULT NULL COMMENT \'Match stopped at HH:MM\', CHANGE reservations reservations TEXT DEFAULT NULL COMMENT \'Reservations\', CHANGE report report TEXT DEFAULT NULL COMMENT \'Report\', CHANGE signed_place signed_place VARCHAR(150) DEFAULT NULL COMMENT \'Signed at\', CHANGE signed_on signed_on DATE DEFAULT NULL COMMENT \'Signed on\', CHANGE form_state form_state VARCHAR(1) DEFAULT NULL COMMENT \'0=draft,1=validated,2=archived\', CHANGE fixture_id fixture_id INT DEFAULT NULL COMMENT \'FK fixture (unique)\', CHANGE coach_id coach_id INT DEFAULT NULL COMMENT \'FK coach (person)\'');
        $this->addSql('ALTER TABLE scoresheet ADD CONSTRAINT `fk_scoresheet_coach_id` FOREIGN KEY (coach_id) REFERENCES person (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE scoresheet ADD CONSTRAINT `fk_scoresheet_fixture_id` FOREIGN KEY (fixture_id) REFERENCES fixture (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE scoresheet RENAME INDEX idx_f001608f3c105691 TO fk_scoresheet_coach_id');
        $this->addSql('ALTER TABLE scoresheet_lineup DROP FOREIGN KEY FK_F9E1431F9ED2C24C');
        $this->addSql('ALTER TABLE scoresheet_lineup DROP FOREIGN KEY FK_F9E1431F296CD8AE');
        $this->addSql('ALTER TABLE scoresheet_lineup DROP FOREIGN KEY FK_F9E1431F99E6F5DF');
        $this->addSql('ALTER TABLE scoresheet_lineup DROP FOREIGN KEY FK_F9E1431FDD842E46');
        $this->addSql('ALTER TABLE scoresheet_lineup CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE player_name_text player_name_text VARCHAR(200) DEFAULT NULL COMMENT \'Fallback\', CHANGE shirt_number shirt_number INT DEFAULT NULL COMMENT \'Shirt number\', CHANGE lineup_role lineup_role VARCHAR(12) DEFAULT NULL COMMENT \'STARTER/SUB\', CHANGE is_captain is_captain TINYINT DEFAULT NULL COMMENT \'Captain\', CHANGE sort_order sort_order INT DEFAULT NULL COMMENT \'Order\', CHANGE scoresheet_id scoresheet_id INT DEFAULT NULL COMMENT \'FK scoresheet\', CHANGE team_id team_id INT DEFAULT NULL COMMENT \'FK team\', CHANGE player_id player_id INT DEFAULT NULL COMMENT \'FK player\', CHANGE position_id position_id INT DEFAULT NULL COMMENT \'FK position\'');
        $this->addSql('ALTER TABLE scoresheet_lineup ADD CONSTRAINT `fk_scoresheet_lineup_player_id` FOREIGN KEY (player_id) REFERENCES player (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE scoresheet_lineup ADD CONSTRAINT `fk_scoresheet_lineup_position_id` FOREIGN KEY (position_id) REFERENCES position (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE scoresheet_lineup ADD CONSTRAINT `fk_scoresheet_lineup_scoresheet_id` FOREIGN KEY (scoresheet_id) REFERENCES scoresheet (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE scoresheet_lineup ADD CONSTRAINT `fk_scoresheet_lineup_team_id` FOREIGN KEY (team_id) REFERENCES team (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE scoresheet_lineup RENAME INDEX idx_f9e1431f296cd8ae TO fk_scoresheet_lineup_team_id');
        $this->addSql('ALTER TABLE scoresheet_lineup RENAME INDEX idx_f9e1431fdd842e46 TO fk_scoresheet_lineup_position_id');
        $this->addSql('ALTER TABLE scoresheet_official DROP FOREIGN KEY FK_6C550AE59ED2C24C');
        $this->addSql('ALTER TABLE scoresheet_official DROP FOREIGN KEY FK_6C550AE5217BBB47');
        $this->addSql('ALTER TABLE scoresheet_official CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE role role VARCHAR(30) DEFAULT NULL COMMENT \'MAIN_REF/AR1/AR2/FOURTH/DELEGATE/DOCTOR\', CHANGE name_text name_text VARCHAR(150) DEFAULT NULL COMMENT \'Fallback\', CHANGE scoresheet_id scoresheet_id INT DEFAULT NULL COMMENT \'FK scoresheet\', CHANGE person_id person_id INT DEFAULT NULL COMMENT \'FK person\'');
        $this->addSql('ALTER TABLE scoresheet_official ADD CONSTRAINT `fk_scoresheet_official_person_id` FOREIGN KEY (person_id) REFERENCES person (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE scoresheet_official ADD CONSTRAINT `fk_scoresheet_official_scoresheet_id` FOREIGN KEY (scoresheet_id) REFERENCES scoresheet (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE scoresheet_official RENAME INDEX idx_6c550ae5217bbb47 TO fk_scoresheet_official_person_id');
        $this->addSql('ALTER TABLE scoresheet_official RENAME INDEX idx_6c550ae59ed2c24c TO fk_scoresheet_official_scoresheet_id');
        $this->addSql('ALTER TABLE scoresheet_substitution DROP FOREIGN KEY FK_E318A73A9ED2C24C');
        $this->addSql('ALTER TABLE scoresheet_substitution DROP FOREIGN KEY FK_E318A73A296CD8AE');
        $this->addSql('ALTER TABLE scoresheet_substitution DROP FOREIGN KEY FK_E318A73A9B0FCEA4');
        $this->addSql('ALTER TABLE scoresheet_substitution DROP FOREIGN KEY FK_E318A73AAF8B0575');
        $this->addSql('ALTER TABLE scoresheet_substitution CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE player_out_text player_out_text VARCHAR(200) DEFAULT NULL COMMENT \'Fallback\', CHANGE player_in_text player_in_text VARCHAR(200) DEFAULT NULL COMMENT \'Fallback\', CHANGE minute minute VARCHAR(8) DEFAULT NULL COMMENT \'Minute e.g. 74, 90+2\', CHANGE scoresheet_id scoresheet_id INT DEFAULT NULL COMMENT \'FK scoresheet\', CHANGE team_id team_id INT DEFAULT NULL COMMENT \'FK team\', CHANGE player_out_id player_out_id INT DEFAULT NULL COMMENT \'FK player out\', CHANGE player_in_id player_in_id INT DEFAULT NULL COMMENT \'FK player in\'');
        $this->addSql('ALTER TABLE scoresheet_substitution ADD CONSTRAINT `fk_scoresheet_substitution_player_in_id` FOREIGN KEY (player_in_id) REFERENCES player (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE scoresheet_substitution ADD CONSTRAINT `fk_scoresheet_substitution_player_out_id` FOREIGN KEY (player_out_id) REFERENCES player (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE scoresheet_substitution ADD CONSTRAINT `fk_scoresheet_substitution_scoresheet_id` FOREIGN KEY (scoresheet_id) REFERENCES scoresheet (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE scoresheet_substitution ADD CONSTRAINT `fk_scoresheet_substitution_team_id` FOREIGN KEY (team_id) REFERENCES team (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE scoresheet_substitution RENAME INDEX idx_e318a73aaf8b0575 TO fk_scoresheet_substitution_player_in_id');
        $this->addSql('ALTER TABLE scoresheet_substitution RENAME INDEX idx_e318a73a9ed2c24c TO fk_scoresheet_substitution_scoresheet_id');
        $this->addSql('ALTER TABLE scoresheet_substitution RENAME INDEX idx_e318a73a296cd8ae TO fk_scoresheet_substitution_team_id');
        $this->addSql('ALTER TABLE scoresheet_substitution RENAME INDEX idx_e318a73a9b0fcea4 TO fk_scoresheet_substitution_player_out_id');
        $this->addSql('ALTER TABLE season CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE name name VARCHAR(20) DEFAULT NULL COMMENT \'1962/1963 or 2025/2026\', CHANGE year_start year_start INT DEFAULT NULL COMMENT \'Start year\', CHANGE year_end year_end INT DEFAULT NULL COMMENT \'End year\'');
        $this->addSql('ALTER TABLE source_file CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE filename filename VARCHAR(255) DEFAULT NULL COMMENT \'Source filename\', CHANGE checksum_sha1 checksum_sha1 VARCHAR(40) DEFAULT NULL COMMENT \'Checksum\', CHANGE imported_at imported_at DATETIME DEFAULT NULL COMMENT \'Imported at\', CHANGE note note VARCHAR(255) DEFAULT NULL COMMENT \'Note\'');
        $this->addSql('ALTER TABLE stadium DROP FOREIGN KEY FK_E604044F8BAC62AF');
        $this->addSql('ALTER TABLE stadium DROP FOREIGN KEY FK_E604044FF92F3E70');
        $this->addSql('ALTER TABLE stadium CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE name name VARCHAR(200) DEFAULT NULL COMMENT \'Stadium\', CHANGE capacity capacity INT DEFAULT NULL COMMENT \'Capacity\', CHANGE city_id city_id INT DEFAULT NULL COMMENT \'FK city\', CHANGE country_id country_id INT DEFAULT NULL COMMENT \'FK country\'');
        $this->addSql('ALTER TABLE stadium ADD CONSTRAINT `fk_stadium_city_id` FOREIGN KEY (city_id) REFERENCES city (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE stadium ADD CONSTRAINT `fk_stadium_country_id` FOREIGN KEY (country_id) REFERENCES country (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE stadium RENAME INDEX idx_e604044f8bac62af TO fk_stadium_city_id');
        $this->addSql('ALTER TABLE stadium RENAME INDEX idx_e604044ff92f3e70 TO fk_stadium_country_id');
        $this->addSql('ALTER TABLE stage DROP FOREIGN KEY FK_C27C936974281A5E');
        $this->addSql('ALTER TABLE stage CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE name name VARCHAR(120) DEFAULT NULL COMMENT \'Stage/Round/Phase (Group, Final, J1...)\', CHANGE stage_type stage_type VARCHAR(30) DEFAULT NULL COMMENT \'group/knockout/league/round\', CHANGE is_final is_final TINYINT DEFAULT NULL COMMENT \'1 if final\', CHANGE sort_order sort_order INT DEFAULT NULL COMMENT \'Ordering\', CHANGE edition_id edition_id INT DEFAULT NULL COMMENT \'FK edition\'');
        $this->addSql('ALTER TABLE stage ADD CONSTRAINT `fk_stage_edition_id` FOREIGN KEY (edition_id) REFERENCES edition (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE stage RENAME INDEX idx_c27c936974281a5e TO fk_stage_edition_id');
        $this->addSql('ALTER TABLE standing DROP FOREIGN KEY FK_619A8AD874281A5E');
        $this->addSql('ALTER TABLE standing DROP FOREIGN KEY FK_619A8AD82298D193');
        $this->addSql('ALTER TABLE standing DROP FOREIGN KEY FK_619A8AD83D90D21B');
        $this->addSql('ALTER TABLE standing DROP FOREIGN KEY FK_619A8AD8296CD8AE');
        $this->addSql('ALTER TABLE standing CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE rank rank INT DEFAULT NULL COMMENT \'Rank\', CHANGE played played INT DEFAULT NULL COMMENT \'Played\', CHANGE won won INT DEFAULT NULL COMMENT \'Won\', CHANGE draw draw INT DEFAULT NULL COMMENT \'Draw\', CHANGE lost lost INT DEFAULT NULL COMMENT \'Lost\', CHANGE goals_for goals_for INT DEFAULT NULL COMMENT \'GF\', CHANGE goals_against goals_against INT DEFAULT NULL COMMENT \'GA\', CHANGE goal_diff goal_diff INT DEFAULT NULL COMMENT \'GD\', CHANGE points points INT DEFAULT NULL COMMENT \'Points\', CHANGE observation observation VARCHAR(200) DEFAULT NULL COMMENT \'Observation\', CHANGE source_note source_note VARCHAR(200) DEFAULT NULL COMMENT \'Source\', CHANGE edition_id edition_id INT DEFAULT NULL COMMENT \'FK edition\', CHANGE stage_id stage_id INT DEFAULT NULL COMMENT \'FK stage\', CHANGE matchday_id matchday_id INT DEFAULT NULL COMMENT \'FK matchday (optional)\', CHANGE team_id team_id INT DEFAULT NULL COMMENT \'FK team\'');
        $this->addSql('ALTER TABLE standing ADD CONSTRAINT `fk_standing_edition_id` FOREIGN KEY (edition_id) REFERENCES edition (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE standing ADD CONSTRAINT `fk_standing_matchday_id` FOREIGN KEY (matchday_id) REFERENCES matchday (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE standing ADD CONSTRAINT `fk_standing_stage_id` FOREIGN KEY (stage_id) REFERENCES stage (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE standing ADD CONSTRAINT `fk_standing_team_id` FOREIGN KEY (team_id) REFERENCES team (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE standing RENAME INDEX idx_619a8ad82298d193 TO fk_standing_stage_id');
        $this->addSql('ALTER TABLE standing RENAME INDEX idx_619a8ad83d90d21b TO fk_standing_matchday_id');
        $this->addSql('ALTER TABLE team DROP FOREIGN KEY FK_C4E0A61F61190A32');
        $this->addSql('ALTER TABLE team DROP FOREIGN KEY FK_C4E0A61F9008F799');
        $this->addSql('ALTER TABLE team CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE team_type team_type VARCHAR(10) DEFAULT NULL COMMENT \'CLUB/NATIONAL\', CHANGE display_name display_name VARCHAR(200) DEFAULT NULL COMMENT \'Resolved name\', CHANGE club_id club_id INT DEFAULT NULL COMMENT \'FK club\', CHANGE national_team_id national_team_id INT DEFAULT NULL COMMENT \'FK national_team\'');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT `fk_team_club_id` FOREIGN KEY (club_id) REFERENCES club (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE team ADD CONSTRAINT `fk_team_national_team_id` FOREIGN KEY (national_team_id) REFERENCES national_team (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE team RENAME INDEX idx_c4e0a61f61190a32 TO fk_team_club_id');
        $this->addSql('ALTER TABLE team RENAME INDEX idx_c4e0a61f9008f799 TO fk_team_national_team_id');
        $this->addSql('ALTER TABLE trophy DROP FOREIGN KEY FK_112AFAE97B39D312');
        $this->addSql('ALTER TABLE trophy CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE name name VARCHAR(200) DEFAULT NULL COMMENT \'Trophy/Title\', CHANGE trophy_type trophy_type VARCHAR(30) DEFAULT NULL COMMENT \'winner/runner_up/top_scorer/champion_squad\', CHANGE competition_id competition_id INT DEFAULT NULL COMMENT \'FK competition\'');
        $this->addSql('ALTER TABLE trophy ADD CONSTRAINT `fk_trophy_competition_id` FOREIGN KEY (competition_id) REFERENCES competition (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE trophy RENAME INDEX idx_112afae97b39d312 TO fk_trophy_competition_id');
        $this->addSql('ALTER TABLE trophy_award DROP FOREIGN KEY FK_E1C746D0F59AEEEF');
        $this->addSql('ALTER TABLE trophy_award DROP FOREIGN KEY FK_E1C746D04EC001D1');
        $this->addSql('ALTER TABLE trophy_award DROP FOREIGN KEY FK_E1C746D074281A5E');
        $this->addSql('ALTER TABLE trophy_award DROP FOREIGN KEY FK_E1C746D0296CD8AE');
        $this->addSql('ALTER TABLE trophy_award DROP FOREIGN KEY FK_E1C746D0217BBB47');
        $this->addSql('ALTER TABLE trophy_award CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE rank rank INT DEFAULT NULL COMMENT \'1=winner\', CHANGE note note VARCHAR(200) DEFAULT NULL COMMENT \'Note/Source\', CHANGE trophy_id trophy_id INT DEFAULT NULL COMMENT \'FK trophy\', CHANGE season_id season_id INT DEFAULT NULL COMMENT \'FK season\', CHANGE edition_id edition_id INT DEFAULT NULL COMMENT \'FK edition\', CHANGE team_id team_id INT DEFAULT NULL COMMENT \'FK team\', CHANGE person_id person_id INT DEFAULT NULL COMMENT \'FK person\'');
        $this->addSql('ALTER TABLE trophy_award ADD CONSTRAINT `fk_trophy_award_edition_id` FOREIGN KEY (edition_id) REFERENCES edition (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE trophy_award ADD CONSTRAINT `fk_trophy_award_person_id` FOREIGN KEY (person_id) REFERENCES person (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE trophy_award ADD CONSTRAINT `fk_trophy_award_season_id` FOREIGN KEY (season_id) REFERENCES season (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE trophy_award ADD CONSTRAINT `fk_trophy_award_team_id` FOREIGN KEY (team_id) REFERENCES team (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE trophy_award ADD CONSTRAINT `fk_trophy_award_trophy_id` FOREIGN KEY (trophy_id) REFERENCES trophy (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trophy_award RENAME INDEX idx_e1c746d074281a5e TO fk_trophy_award_edition_id');
        $this->addSql('ALTER TABLE trophy_award RENAME INDEX idx_e1c746d0f59aeeef TO fk_trophy_award_trophy_id');
        $this->addSql('ALTER TABLE trophy_award_person DROP FOREIGN KEY FK_8ADBCE5748EB4F71');
        $this->addSql('ALTER TABLE trophy_award_person DROP FOREIGN KEY FK_8ADBCE57217BBB47');
        $this->addSql('ALTER TABLE trophy_award_person CHANGE id id INT AUTO_INCREMENT NOT NULL COMMENT \'#\', CHANGE role role VARCHAR(20) DEFAULT NULL COMMENT \'PLAYER/COACH/STAFF\', CHANGE trophy_award_id trophy_award_id INT DEFAULT NULL COMMENT \'FK trophy_award\', CHANGE person_id person_id INT DEFAULT NULL COMMENT \'FK person\'');
        $this->addSql('ALTER TABLE trophy_award_person ADD CONSTRAINT `fk_trophy_award_person_person_id` FOREIGN KEY (person_id) REFERENCES person (id) ON UPDATE CASCADE ON DELETE SET NULL');
        $this->addSql('ALTER TABLE trophy_award_person ADD CONSTRAINT `fk_trophy_award_person_trophy_award_id` FOREIGN KEY (trophy_award_id) REFERENCES trophy_award (id) ON UPDATE CASCADE ON DELETE CASCADE');
        $this->addSql('ALTER TABLE trophy_award_person RENAME INDEX idx_8adbce57217bbb47 TO fk_trophy_award_person_person_id');
        $this->addSql('ALTER TABLE trophy_award_person RENAME INDEX idx_8adbce5748eb4f71 TO fk_trophy_award_person_trophy_award_id');
    }
}
